language: groovy
os: linux
jdk:
  - openjdk8
  - openjdk11

branches:
  only:
    - master

# See https://docs.travis-ci.com/user/languages/groovy/#gradle-caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - pushd ExternalScripts
  - ./gradlew assemble -PnexusExtUsername=${NEXUS_EXT_USERNAME} -PnexusExtPassword=${NEXUS_EXT_PASSWORD}
  - popd
  - pushd UsingAnIdeToWriteScripts
  - ./gradlew assemble -PnexusExtUsername=${NEXUS_EXT_USERNAME} -PnexusExtPassword=${NEXUS_EXT_PASSWORD}
  - popd

script:
  - pushd ExternalScripts
  - ./gradlew check -PnexusExtUsername=${NEXUS_EXT_USERNAME} -PnexusExtPassword=${NEXUS_EXT_PASSWORD}
  - popd
  - pushd UsingAnIdeToWriteScripts
  - ./gradlew check -PnexusExtUsername=${NEXUS_EXT_USERNAME} -PnexusExtPassword=${NEXUS_EXT_PASSWORD}
  - popd

notifications:
  email:
    recipients:
      - nsmith@dalet.com
      - olockwood@dalet.com
    on_success: change
    on_failure: always
